### ISSUE TITLE
Cannot compile image: error with pear/net_smtp 1.8.1

### ISSUE THREAD

**Issue by clauded** [ubc/mediawiki-docker#13]
On Ubuntu 18.04, compilation fails:

`Step 19/25 : RUN curl -L https://getcomposer.org/installer | php     && php composer.phar install --no-dev
 ---> Running in 9f25ec1a27f1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  257k  100  257k    0     0   540k      0 --:--:-- --:--:-- --:--:--  541k
All settings correct for using Composer
Downloading...

Composer (version 1.8.5) successfully installed to: /var/www/html/composer.phar
Use it: php composer.phar

Do not run Composer as root/super user! See https://getcomposer.org/root for details
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear/net_smtp 1.8.1 is satisfiable by pear/net_smtp[1.8.1] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
ERROR: Service 'web' failed to build: The command '/bin/sh -c curl -L https://getcomposer.org/installer | php     && php composer.phar install --no-dev' returned a non-zero code: 2`

**Comment by xcompass** [comment]
Just tried `docker build -t mediawiki .` on master branch. Works fine for me. Which branch did you try? Did you make any change in any files?

**Comment by clauded** [comment]
Yeah, tried to use v1.32.0 of Mediawiki :(
Do you have any idea of what would be in conflict?

**Comment by kitsook** [comment]
That is because the `composer.json` file from mediawiki 1.32 specified to use `pear/net_smtp` version 1.8.0.  But the `composer.local.json` from this build specified 1.8.1.

There are two options.  You could modify `composer.local.json` and downgrade `pear/net_smtp` to 1.8.0. Or, you can add a command in Dockerfile (before the composer command) to modify `composer.json` to use 1.8.1:
`RUN sed -i 's#"pear/net_smtp": "1.8.0"#"pear/net_smtp": "1.8.1"#g' composer.json`

**Comment by xcompass** [comment]
I saw the same issue on 1.32. Thanks @kitsook for the tip. I've removed the net_stmp from composer.local.json. I remember it was because it was missing from the main composer file. It works now. @clauded I'm testing 1.32 now. If you want to wait a little bit, I'll push a new commit to fix it.

**Comment by xcompass** [comment]
The 1.32 update is pushed to master, please feel free to give it a try.
