### ISSUE TITLE
user wont work, cant edit or create articles

### ISSUE THREAD

**Issue by lattice0** [ubc/mediawiki-docker#17]
Without passing any user environment variables, I couldnt login with your default admin info, onyl with `admin admin`, however I couldn't edit or create anything.

I tried passing my own login

```
- MEDIAWIKI_ADMIN_USER=user
- MEDIAWIKI_ADMIN_PASS=pass
```
but it didn't work also

**Comment by kitsook** [comment]
Hi @lucaszanella. I assume you are using the default `docker-compose.yml` file to start the containers?  If so, it is set to use LDAP for authentication.  So you can't create local user within wiki.  You need to add users to LDAP.  By default, there is one user defined in the OpenLDAP container and it is `admin/admin`.

Note that even if you edit `docker-compose.yml` and switch off LDAP authentication, changing the `MEDIAWIKI_ADMIN_USER` or `MEDIAWIKI_ADMIN_PASS` won't take effect as these variables are used only once during the first time the container starts.  To change admin password, you can run the maintenance script manually.  Refer to mediawiki doc or the logic in `docker-entrypoint.sh` for details.

As for not able to create / edit any pages.  The default `LocalSettings.php` disables the createpage right of anonymous users.  But there seems to be a bug in mediawiki preventing registered users too.  To fix it, add  `MEDIAWIKI_ALLOW_ANONYMOUS_EDIT=1` to `docker-compose.yml` environment setting for the `web` container.  Restart your containers and pretend to create a new page.  You can remove / disable `MEDIAWIKI_ALLOW_ANONYMOUS_EDIT` afterward and even so registered users will still be able to create new pages.

**Comment by xcompass** [comment]
close due to inactivity.
