### ISSUE TITLE
Default settings problem

### ISSUE THREAD

**Issue by GPaddle** [ubc/mediawiki-docker#22]
Hello,
I'm currently trying to launch your image  to get the LDAP feature but I get everytime this kind of log :

```
AH00526: Syntax error on line 30 of /etc/apache2/mediawiki.conf:
ProxyPass URL must be absolute!: restbase-is-not-specified/localhost/v1
Action '-e info -D FOREGROUND' failed.
The Apache error log may have more information.
```

After some search I found that it could be resolved with an older version but it doesn't change anything,
Do you have some idea to fix the problem ?

Regards

**Comment by xcompass** [comment]
We are currently still on 1.31: https://github.com/ubc/mediawiki-docker/tree/REL1_31. Could you try this branch? We haven't got time to fix the master. We may just wait for 1.35 LTS released to catch up with master.
