### ISSUE TITLE
composer-merge error, Why?

### ISSUE THREAD

**Issue by crashangelbr** [ubc/mediawiki-docker#27]
Hi, a trying install this docker and receive this error...

`
The "wikimedia/composer-merge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wikimedia/composer-merge-plugin 1.4.1 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.1].
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
ERROR: Service 'web' failed to build: The command '/bin/sh -c curl -L https://getcomposer.org/installer | php     && php composer.phar install --no-dev' returned a non-zero code: 2
`

**Comment by xcompass** [comment]
Are you running on master branch? It was a little bit behind the latest development. I've merged REL1_35 branch to master. Could you try again?

**Comment by xcompass** [comment]
closing this. Please feel free to reopen it if you still have trouble.
